services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: "*ProjetoEstudo2025"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis_data:/data
    networks:
      - app-network

  user-api:
    image: fatecstore/user-api:20250528.1
    container_name: user-api
    ports:
      - "8080:8080"
    environment:
      - AppsettingsConfigurations__ServiceClients__Cart=http://carts-api:8080/api/carts
      - AppsettingsConfigurations__EmailConfiguration__FromMail=fatec.store2025@gmail.com
      - AppsettingsConfigurations__EmailConfiguration__FromMailPassword=kdtgrztjtssiylac
      - AppsettingsConfigurations__JwtConfiguration__Audience=TesteAudience
      - AppsettingsConfigurations__JwtConfiguration__Issuer=TesteIssuer
      - AppsettingsConfigurations__JwtConfiguration__SecretJwtKey=YjA2Nzk0MmJjMTUyNDgyNThhY2NmOWNlNmZkMDg2NDFhdXRodGVzdGU=
      - AppsettingsConfigurations__RedisConfiguration__ExpirationInMinutes=60
      - AppsettingsConfigurations__RedisConfiguration__Server=redis:6379
      - AppsettingsConfigurations__Database=server=mysql;port=3306;database=Fatec.Store.User;user=root;password=*ProjetoEstudo2025;AllowPublicKeyRetrieval=True;SslMode=None
    depends_on:
      - mysql
      - redis
    networks:
      - app-network

  products-api:
    image: fatecstore/products-api:20250528.1
    container_name: products-api
    ports:
      - "8081:8080"
    environment:
      - ConnectionStrings__DefaultConnection=server=mysql;port=3306;database=Fatec.Store.Products;user=root;password=*ProjetoEstudo2025;AllowPublicKeyRetrieval=True;SslMode=None
    depends_on:
      - mysql
      - redis
    networks:
      - app-network

  carts-api:
    image: fatecstore/carts-api:20250528.1
    container_name: carts-api
    ports:
      - "8082:8080"
    environment:
      - ConnectionStrings__DefaultConnection=server=mysql;port=3306;database=Fatec.Store.Carts;user=root;password=*ProjetoEstudo2025;AllowPublicKeyRetrieval=True;SslMode=None
    depends_on:
      - mysql
      - redis
    networks:
      - app-network

  orders-api:
    image: fatecstore/orders-api:20250528.1
    container_name: orders-api
    ports:
      - "8083:8080"
    environment:
      - AppsettingsConfigurations__JwtConfiguration__Audience=TesteAudience
      - AppsettingsConfigurations__JwtConfiguration__Issuer=TesteIssuer
      - AppsettingsConfigurations__JwtConfiguration__SecretJwtKey=YjA2Nzk0MmJjMTUyNDgyNThhY2NmOWNlNmZkMDg2NDFhdXRodGVzdGU=
      - AppsettingsConfigurations__Database=server=mysql;port=3306;database=Fatec.Store.Orders;user=root;password=*ProjetoEstudo2025;AllowPublicKeyRetrieval=True;SslMode=None
      - AppsettingsConfigurations__ServiceClients__ViaCep=https://viacep.com.br/ws/{0}/json
      - AppsettingsConfigurations__ServiceClients__Coupon=http://discount-api:8080/api/coupon
      - AppsettingsConfigurations__ServiceClients__Products=http://products-api:8080/api/products
    depends_on:
      - mysql
      - redis
    networks:
      - app-network

  discount-api:
    image: fatecstore/discount-api:20250528.1
    container_name: discount-api
    ports:
      - "8084:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Initial Catalog=Fatec.Store.Coupons;User ID=SA;Password=*SQLestudo2024;Encrypt=False;TrustServerCertificate=False;Connection Timeout=30;
    depends_on:
      - redis
      - mysql
    networks:
      - app-network

  store-web:
    image: fatecstore/web:20250528.1
    container_name: store-web
    ports:
      - 80:80
    depends_on:
      - carts-api
      - products-api
      - user-api
      - discount-api
      - orders-api
    networks:
      - app-network

volumes:
  mysql_data:
  redis_data:

networks:
  app-network:
    driver: bridge
