services:
  user-api:
    image: fatecstore/user-api:20250528.1
    container_name: user-api
    ports:
      - "8080:8080"
    environment:
      - AppsettingsConfigurations__ServiceClients__Cart=http://carts-api:8080/api/carts
      - AppsettingsConfigurations__EmailConfiguration__FromMail=fatec.store2025@gmail.com
      - AppsettingsConfigurations__EmailConfiguration__FromMailPassword=kdtgrztjtssiylac
      - AppsettingsConfigurations__JwtConfiguration__Audience=TesteAudience
      - AppsettingsConfigurations__JwtConfiguration__Issuer=TesteIssuer
      - AppsettingsConfigurations__JwtConfiguration__SecretJwtKey=YjA2Nzk0MmJjMTUyNDgyNThhY2NmOWNlNmZkMDg2NDFhdXRodGVzdGU=
      - AppsettingsConfigurations__RedisConfiguration__ExpirationInMinutes=60
      - AppsettingsConfigurations__RedisConfiguration__Server=56.124.55.210:6379
      - AppsettingsConfigurations__Database=server=56.124.55.210;port=3306;database=Fatec.Store.User;user=root;password=*ProjetoEstudo2025;AllowPublicKeyRetrieval=True;SslMode=None
    networks:
      - app-network
    depends_on:
      - carts-api

  products-api:
    image: fatecstore/products-api:20250528.1
    container_name: products-api
    ports:
      - "8081:8080"
    environment:
      - ConnectionStrings__DefaultConnection=server=56.124.55.210;port=3306;database=Fatec.Store.Products;user=root;password=*ProjetoEstudo2025;AllowPublicKeyRetrieval=True;SslMode=None
    networks:
      - app-network

  carts-api:
    image: fatecstore/carts-api:20250528.1
    container_name: carts-api
    ports:
      - "8082:8080"
    environment:
      - ConnectionStrings__DefaultConnection=server=56.124.55.210;port=3306;database=Fatec.Store.Carts;user=root;password=*ProjetoEstudo2025;AllowPublicKeyRetrieval=True;SslMode=None
    networks:
      - app-network

  orders-api:
    image: fatecstore/orders-api:20250528.1
    container_name: orders-api
    ports:
      - "8083:8080"
    environment:
      - AppsettingsConfigurations__PaymentsConfiguration__FormsOfPaymentsAllowed__0=pix
      - AppsettingsConfigurations__PaymentsConfiguration__FormsOfPaymentsAllowed__1=cartao
      - AppsettingsConfigurations__PaymentsConfiguration__PaymentsMethodsCardAllowed__0=credito
      - AppsettingsConfigurations__PaymentsConfiguration__PaymentsMethodsCardAllowed__1=debito
      - AppsettingsConfigurations__PaymentsConfiguration__InstallmentOptions__0=1
      - AppsettingsConfigurations__PaymentsConfiguration__InstallmentOptions__1=2
      - AppsettingsConfigurations__PaymentsConfiguration__InstallmentOptions__2=3
      - AppsettingsConfigurations__PaymentsConfiguration__InstallmentOptions__3=4
      - AppsettingsConfigurations__PaymentsConfiguration__InstallmentOptions__4=5
      - AppsettingsConfigurations__PaymentsConfiguration__InstallmentOptions__5=6
      - AppsettingsConfigurations__PaymentsConfiguration__InstallmentOptions__6=7
      - AppsettingsConfigurations__PaymentsConfiguration__InstallmentOptions__7=8
      - AppsettingsConfigurations__PaymentsConfiguration__InstallmentOptions__8=9
      - AppsettingsConfigurations__PaymentsConfiguration__InstallmentOptions__9=10
      - AppsettingsConfigurations__PaymentsConfiguration__PixConfiguration__PixKey=alexandre.betassa.souza@hotmail.com
      - AppsettingsConfigurations__PaymentsConfiguration__PixConfiguration__Description=Fatec Store
      - AppsettingsConfigurations__PaymentsConfiguration__PixConfiguration__City=Taquaritinga-SP
      - AppsettingsConfigurations__PaymentsConfiguration__PixConfiguration__TxId=Pagamento
      - AppsettingsConfigurations__JwtConfiguration__Audience=TesteAudience
      - AppsettingsConfigurations__JwtConfiguration__Issuer=TesteIssuer
      - AppsettingsConfigurations__JwtConfiguration__SecretJwtKey=YjA2...
      - AppsettingsConfigurations__JwtConfiguration__ExpirationInMinutes=60
      - AppsettingsConfigurations__JwtConfiguration__WriteRoles__0=User
      - AppsettingsConfigurations__JwtConfiguration__WriteRoles__1=Admin
      - AppsettingsConfigurations__JwtConfiguration__ReadRoles__0=User
      - AppsettingsConfigurations__JwtConfiguration__ReadRoles__1=Admin
      - AppsettingsConfigurations__Database=server=56.124.55.210;port=3306;database=Fatec.Store.Orders;user=root;password=*ProjetoEstudo2025;AllowPublicKeyRetrieval=True;SslMode=None
      - AppsettingsConfigurations__ServiceClients__ViaCep=https://viacep.com.br/ws/{0}/json
      - AppsettingsConfigurations__ServiceClients__Coupon=http://discount-api:8080/api/coupons
      - AppsettingsConfigurations__ServiceClients__Products=http://products-api:8080/api/products
    networks:
      - app-network
    depends_on:
      - products-api
      - discount-api

  discount-api:
    image: fatecstore/discount-api:20250528.1
    container_name: discount-api
    ports:
      - "8084:8080"
    environment:
      - ConnectionStrings__DefaultConnection=server=56.124.55.210;port=3306;database=Fatec.Store.Coupons;user=root;password=*ProjetoEstudo2025;AllowPublicKeyRetrieval=True;SslMode=None
    networks:
      - app-network

  store-web:
    image: fatecstore/web:20250518.2
    container_name: store-web
    ports:
      - 80:80
    depends_on:
      - carts-api
      - products-api
      - user-api
      - discount-api
      - orders-api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge