services:
  user-api:
    image: fatecstore/user-api:20250504.1
    container_name: user-api
    ports:
      - "8080:8080"
    environment:
      - AppsettingsConfigurations__EmailConfiguration__FromMail=fatec.store2025@gmail.com
      - AppsettingsConfigurations__EmailConfiguration__FromMailPassword=gyrgxkerkjtfoyui
      - AppsettingsConfigurations__JwtConfiguration__Audience=TesteAudience
      - AppsettingsConfigurations__JwtConfiguration__Issuer=TesteIssuer
      - AppsettingsConfigurations__JwtConfiguration__SecretJwtKey=YjA2Nzk0MmJjMTUyNDgyNThhY2NmOWNlNmZkMDg2NDFhdXRodGVzdGU=
      - AppsettingsConfigurations__RedisConfiguration__ExpirationInMinutes=60
      - AppsettingsConfigurations__RedisConfiguration__Server=56.124.55.210:6379
      - AppsettingsConfigurations__Database=server=56.124.55.210;port=3306;database=Fatec.Store.User;user=root;password=*ProjetoEstudo2025;AllowPublicKeyRetrieval=True;SslMode=None
    networks:
      - app-network

  products-api:
    image: fatecstore/products-api:20250504.1
    container_name: products-api
    ports:
      - "8081:8080"
    environment:
      - ConnectionStrings__DefaultConnection=server=56.124.55.210;port=3306;database=Fatec.Store.Products;user=root;password=*ProjetoEstudo2025;AllowPublicKeyRetrieval=True;SslMode=None
    networks:
      - app-network

  carts-api:
    image: fatecstore/carts-api:20250504.1
    container_name: carts-api
    ports:
      - "8082:8080"
    environment:
      - ConnectionStrings__DefaultConnection=server=56.124.55.210;port=3306;database=Fatec.Store.Carts;user=root;password=*ProjetoEstudo2025;AllowPublicKeyRetrieval=True;SslMode=None
    networks:
      - app-network

  orders-api:
    image: fatecstore/orders-api:20250503.1
    container_name: orders-api
    ports:
      - "8083:8080"
    environment:
      - AppsettingsConfigurations__JwtConfiguration__Audience=TesteAudience
      - AppsettingsConfigurations__JwtConfiguration__Issuer=TesteIssuer
      - AppsettingsConfigurations__JwtConfiguration__SecretJwtKey=YjA2Nzk0MmJjMTUyNDgyNThhY2NmOWNlNmZkMDg2NDFhdXRodGVzdGU=
      - AppsettingsConfigurations__Database=server=56.124.55.210;port=3306;database=Fatec.Store.Orders;user=root;password=*ProjetoEstudo2025;AllowPublicKeyRetrieval=True;SslMode=None
      - AppsettingsConfigurations__ServiceClients__ViaCep=https://viacep.com.br/ws/{0}/json
      - AppsettingsConfigurations__ServiceClients__Coupon=http://coupon-api:8080/api/coupon
      - AppsettingsConfigurations__ServiceClients__Products=http://products-api:8080/api/Products
    networks:
      - app-network

  coupon-api:
    image: fatecstore/coupon-api:20250504.4
    container_name: coupon-api
    ports:
      - "8084:8080"
    environment:
      - ConnectionStrings__DefaultConnection=server=56.124.55.210;port=3306;database=Fatec.Store.Coupons;user=root;password=*ProjetoEstudo2025;AllowPublicKeyRetrieval=True;SslMode=None
    networks:
      - app-network

  store-web:
    image: fatecstore/web:20250504.2
    container_name: store-web
    ports:
      - 80:80
    depends_on:
      - carts-api
      - products-api
      - user-api
      - coupon-api
      - orders-api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge